### PR TITLE
Added some tests

### PR DESCRIPTION
**Pull request by ncave**

### CODE REVIEW

**Comment by ncave** [comment]
@forki Did you intend to squash? Seems like that created more files in your PR.

**Comment by ncave** [comment]
@forki Perhaps I forgot to pull your fork first.

**Comment by forki** [comment]
That was fat fingered on the phone.

Am 20.01.2018 19:30 schrieb "ncave" <notifications@github.com>:

**Comment by ncave** [comment]
@forki seems ok now, thanks.

**Pull request merged**
