### PR TITLE
packages at design time

### PR DESCRIPTION
**Pull request by dsyme**
just a draft at this stage, will work on it more, sharing for visibility

### CODE REVIEW

**Comment by forki** [comment]
Urgs seems like a merge conflict. Will try to resolve

**Comment by dsyme** [comment]
Don't worry I'll do it.  I'm still working on this, need to check its ramifications

**Comment by forki** [comment]
ok.

**Comment by forki** [comment]
merging to see it in CI

**Comment by forki** [comment]
will readd the implicit paket.dependencies file finder

**Comment by forki** [comment]
ok fixed in 8bc099c72e41895c7ecba3d6aafb639a3382770e

**Comment by forki** [comment]
with 8bc099c it will detect the local deps file if one is around

**Comment by forki** [comment]
Ok paket resolution just crashed my debug hive. I take this as success and that your idea is working. Will debug tomorrow where it goes wrong. 

Great progress for couple of hours messing around.

**Pull request merged**
