### PR TITLE
pin .net cli to version 1.0.0-rc2-002476

### PR DESCRIPTION
**Pull request by enricosada**

### CODE REVIEW

**Comment by forki** [comment]
Thanks buddy. I tried that but couldn't guess the url.

**Comment by enricosada** [comment]
np, should work. if not, ping me np

**Comment by forki** [comment]
Can you please sent this PR to the main fork? Master is broken and I'm trying to write a blog post.

**Comment by enricosada** [comment]
sure

**Comment by forki** [comment]
Cool I will then rebase on master when it's merged.

**Pull request merged**
